apiVersion: v1
kind: Service
metadata:
  name: dec-2nd-poc2019
  labels:
    app: apache2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31290
    protocol: TCP
  selector:
    app: apache2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dec-2nd-poc2019
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: manash081/poc3-dec
        ports:
        - containerPort: 80
